version: "3.9"

services:
  api:
    container_name: cnpa_api
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/app/api
  bot:
    container_name: cnpa_twitter-bot
    build: ./bots/twitter
    ports:
      - 9000:9000
    volumes:
      - ./bots/twitter:/app/bots/twitter
