module.exports = {
  BASUD: "BASUD",
  CAPALONGA: "CAPALONGA",
  DAET: "DAET",
  JOSE_PANGANIBAN: "JOSE_PANGANIBAN",
  LABO: "LABO",
  MERCEDES: "MERCEDES",
  PARACALE: "PARACALE",
  SAN_LORENZO_RUIZ: "SAN_LORENZO_RUIZ",
  SAN_VICENTE: "SAN_VICENTE",
  SANTA_ELENA: "SANTA_ELENA",
  TALISAY: "TALISAY",
  VINZONS: "VINZONS",
};
